### ISSUE TITLE
cannot bundle express  in node mode

### ISSUE THREAD

**Issue by erdii** [erdii/ts-scaffolder-scripts#1]
```
Rollup version:		0.63.4
Mode:			watch-node
Output folder:		dist


[rollup] Starting watcher...
[rollup] Starting bundling process...
[rollup] Fatal rollup error { code: 'FATAL',
  error:
   { Error: Unexpected token
       at error (/private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/rollup/dist/rollup.js:3365:15)
       at Module.error (/private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/rollup/dist/rollup.js:13401:9)
       at tryParse (/private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/rollup/dist/rollup.js:13067:16)
       at Module.setSource (/private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/rollup/dist/rollup.js:13132:33)
       at /private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/rollup/dist/rollup.js:21395:20
     code: 'PARSE_ERROR',
     pos: 9,
     loc:
      { file:
         '/private/var/folders/lt/22978hhn2r79pbzlg6m1lh500000gn/T/tmp.v390psS7/express-example/node_modules/express/node_modules/statuses/codes.json',
        line: 2,
        column: 7 },
     frame:
      '1: {\n2:   "100": "Continue",\n          ^\n3:   "101": "Switching Protocols",\n4:   "102": "Processing",' } }
exiting
```

**Comment by erdii** [comment]
https://github.com/rollup/rollup-plugin-json ?
